function rot1811
f1 = 2000 ; 
f2 = 8000 ; 
T1 = 1/f1 ; 
T2 = 1/f2 ; 
fs = 40000;
Ts = 1/fs ; 
t = linspace(0,T1,200) ;
A = 1 ; B = 2 ; 
arg1 = 0 ; arg2 = 0 ; 
xt = A*cos(2*pi*f1*t + arg1)+B*cos(2*pi*f2*t + arg2);
ts=0:Ts:T1;
xs =A*cos(2*pi*f1*ts + arg1)+B*cos(2*pi*f2*ts + arg2);
figure('Name','The signal in time domain','NumerTitle','off');
subplot(311);
plot(t,xt);
xlabel('time');
ylabel('amplitude');
title('The continuous time signal');
subplot(312);
stem(ts,xs);
xlabel('time');
ylabel('amplitude');
title('The naturally sampled signal');
subplot(313);
stairs(ts,xs);
xlabel('time');
ylabel('amplitude');
title('The flat-top sampled signal');